#
# Docker compose configuration file for NIST Pages PDF support.
#
# From https://github.com/bspk/nistpages-docker/blob/master/pdf/docker-compose-pdf.yml
#

version: '3'

services:
  pdfrender:
    image: jricher/nistpages-pdf
    volumes:
        - .:/opt/source
    environment:
        - "PDFTARGET=${PDFTARGET}"
        - PYTHONUNBUFFERED=1
    command: python /opt/pdf/preprocess-pdf.py
    working_dir: /opt/source
    
